### ISSUE TITLE
@protocol imports still appear in list

### ISSUE THREAD

**Issue by drekka** [shpakovski/Xprop#14]
For example, `MyProtocol` in the following code still appears in the list where as `MyOtherClass` does not:

    @protocol MyProtocol;
    @class MyOtherClass;

    @interface MyClass : NSObject
    -(MyOtherClass *) doSomething:(id<MyProtocol>) withThing;
    @end

Not sure how to differentiate between a protocol declaration and an import. Probably the simplest would be to check for the existence of ';' in the line. So that

    @protocol MyProtocol; // This is my protocol

is still seen as an import.

**Comment by shpakovski** [comment]
Xprop is using menu item titles, and it cannot recognize the source line 😃 Sorry!

**Comment by drekka** [comment]
nuts :-)
