### ISSUE TITLE
Doesn't work on Xcode 6.4

### ISSUE THREAD

**Issue by Hs-Yeah** [shpakovski/Xprop#9]
I added Xcode 6.4 DVTPlugInCompatibilityUUID in the Info.plist and built it, but the plugin doesn't work on Xcode 6.4.

**Comment by shpakovski** [comment]
Thank you very much for the report, I will check this out when I have time. Sorry for inconvenience.

**Comment by shpakovski** [comment]
Xcode 7 was released 1 year ago, and Xcode 8 is around the corner. I'm closing this one, sorry.
